### PR TITLE
Refactored take_snapshot

### PR DESCRIPTION
**Pull request by mitchelloharawild**
With changing to `utils::read.table`, most of the more complex code could be simplified, so this ended up being a complete refactor of `take_snapshot`. Hopefully for the better :smile:
 
* Most code repetition is now removed, along with almost all string parsing.
* Subfolders are now appropriately shown with human parent folders

### CODE REVIEW

**Comment by maelle** [comment]
Wow, thank you! Does this cover #4 as well btw?

**Comment by maelle** [comment]
I'll review soon but please add yourself as "aut" 😺

**Comment by mitchelloharawild** [comment]
> Wow, thank you! Does this cover #4 as well btw?
No worries :smiley:

It doesn't cover #4, but that can be done in a subsequent PR (fairly simple to do, so it might be nice for some one else to try.

It's late in Australia, but if no one else has fixed up year by tomorrow morning I can make another PR for it.

**Comment by maelle** [comment]
I'm getting

**Comment by maelle** [comment]
I'm getting

``` r
utils::read.table("ftp://cran.r-project.org/incoming/")
#> Error in utils::read.table("ftp://cran.r-project.org/incoming/"): no lines available in input
```

<sup>Created on 2018-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
Odd, not sure why that is required. Thanks for the fixes.

**Comment by maelle** [comment]
Thanks again @mitchelloharawild!

**Pull request merged**
