### PR TITLE
Tweak dashboard

### PR DESCRIPTION
**Pull request by hadley**
* Match colours to diagram and only colour folder column
* Use prettyunits to compute relative times (applied at formatting time so that sorting still works correctly)
* Generally tidy up data manipulation code so it's easier to iterate without having to re-run `take_snapshot()`
* Only show subfolder if it's not the same as folder

### CODE REVIEW

**Comment by maelle** [comment]
Thanks, this looks great!

Could you please add yourself as ctb to DESCRIPTION before I merge this?

**Comment by hadley** [comment]
Done!

**Comment by hadley** [comment]
BTW for PRs like there where there are a bunch of commits but only really one major change, you'll get a cleaner git history if you squash and merge.

**Comment by maelle** [comment]
Oh right, I do that in other repos but forgot to pay attention (probably a default to change, I'll look).

**Pull request merged**
